#!/bin/bash

### zim (zsh config manager)
# https://github.com/zimfw/zimfw
zsh ~/.config/zsh/zim/zimfw.zsh upgrade
zsh ~/.config/zsh/zim/zimfw.zsh install
zsh ~/.config/zsh/zim/zimfw.zsh update

### Setup fzf (fuzzy finder)
# https://github.com/junegunn/fzf
FZFDIR=~/.config/fzf
git clone --depth 1 "https://github.com/junegunn/fzf.git" "$FZFDIR" 2> /dev/null || (cd "$FZFDIR" ; git pull)
$FZFDIR/install --xdg --completion --key-bindings --update-rc


PACKAGER_DIR="~/.config/nvim/pack/packager/opt/vim-packager"

if ! [ -e "$PACKAGER_DIR" ]; then
  echo "Begin fetching vim-packager..."
  mkdir -p "$PACKAGER_DIR"
  git clone https://github.com/kristijanhusak/vim-packager "$PACKAGER_DIR"
fi
vim '+:PackagerInstall'
echo "Installed und updated vim-packager and all vim plugins."
