#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# shellcheck disable=SC1090
( "${HOME}/.config/polybar/launch.sh" 1>&2 2>/dev/null )
